"""Mathematics Foundations"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_Mathematics_Foundations.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/00_Mathematics_Foundations.ipynb 3
def foo(): pass
